### ISSUE TITLE
New tab for light novel or filter light novel in the manga tab

### ISSUE THREAD

**Issue by ludg1e** [axiel7/AniHyou-android#133] opened 2024-05-05 19:48 UTC
**Request (required)**
I have some light novels added/saved in my AniList, but currently there's no way to filter them in the app through the manga tab.
I'd like a way to filter them either from the manga tab or through a new tab (though it may look cluttered with a new tab maybe?)

**Additional context (optional)**

**Examples (optional)**

**Comment by axiel7** [comment] 2024-05-05 19:52
Currently you can filter novels this way:
- Click on search icon at the top 🔎
- Click on "More filters" and "Format" and select "Novel"

I know this is not ideal, I'll consider adding other ways to filter your list

**Comment by ludg1e** [comment] 2024-05-05 19:58
Hello! Wow how fast

Gotcha, it works, thank you.
I'll leave this open

**Comment by axiel7** [comment] 2024-05-07 07:37
I'm closing this as a duplicate of #78

**Closed by axiel7** 2024-05-07 07:37 UTC
Labels: enhancement
